#!/bin/bash

npm init
npm create vite@latest frontend -- --template react
cd frontend
npm install
npm install axios @mui/material @mui/icons-material @emotion/styled @emotion/react
cd ..
npm install nodemon dotenv morgan express mongoose
curl 'https://github.com/samjtro/mern/blob/main/index.js' >index.js
curl 'https://github.com/samjtro/mern/blob/main/app.js' >app.js
mkdir models
cd models
curl 'https://github.com/samjtro/mern/blob/main/models/model.js' >model.js
cd frontend/src
rm -rf assets
rm -rf App.jsx main.jsx
curl 'https://github.com/samjtro/mern/blob/main/frontend/src/App.jsx' >App.jsx
curl 'https://github.com/samjtro/mern/blob/main/frontend/src/main.jsx' >main.jsx
curl 'https://github.com/samjtro/mern/blob/main/frontend/src/db.js' >db.js
